### ISSUE TITLE
Main Class missing

### ISSUE THREAD

**Issue by zeldatp151** [iscrapepornsites/r34tool#1]
When I compile that jar using maven, and then run it using the included instructions in the readme, I get "no main manifest attribute, in aps-0.0.1-SNAPSHOT.jar". I noticed that there is no main class specified in the pom.xml, what is supposed to be the main class?

**Comment by iscrapepornsites** [comment]
Hello, sorry i forgot to add this

`me.mux.aps.entry.Entry` is the main class, please create a PR if you want, i don't really know how to handy the pom.xml

**Comment by zeldatp151** [comment]
Thank you, The main class issue seems to be fixed, I have encountered a different issue now, but I need to make sure it's not on my end as I'm still learning java. I'm going to mark this issue as closed, as the issue for which I created it has been resolved.
